version: 1

tasks:
  - name: Backend Setup
    init: pip install -r backend/requirements.txt
    command: python backend/app/main.py

  - name: Frontend Setup
    init: npm install --prefix frontend
    command: npm start --prefix frontend
