version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Use the port your Python app actually runs on
    volumes:
      - ./backend:/app
    command: python app/main.py  # Explicitly run your backend app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start  # Start the frontend app
